read-only flag in EncryptedFs introduced
xoriors/rencfs pull request #182
Opened 2024-08-23 16:40 UTC by someotherself

2024-08-23 17:17 UTC, radumarias requested changes
Added which methods should ret `Err`, all other should work https://github.com/radumarias/rencfs/issues/168

2024-08-23 17:17 UTC, radumarias commented on src/encryptedfs.rs
> +    read_only: Mutex<bool>,
maybe we don't need mutex as we will not change it

2024-08-23 17:17 UTC, radumarias commented on src/encryptedfs.rs
> +    pub async fn read_only(&self, read_only: bool) {
don't need this, it's enough to set it one time in `new`

2024-08-23 17:17 UTC, radumarias commented on src/encryptedfs.rs
> +    async fn is_read_only(&self) -> bool {
this is fine to keep

2024-08-23 17:17 UTC, radumarias commented on src/encryptedfs.rs
> +        if self.is_read_only().await {
this is a read only operation, should work

2024-08-24 06:50 UTC, someotherself commented on src/encryptedfs.rs
> +    read_only: Mutex<bool>,
Alright. read_only is added an an arguement now.

2024-08-24 06:51 UTC, someotherself commented on src/encryptedfs.rs
> +    pub async fn read_only(&self, read_only: bool) {
This is deleted now.

2024-08-24 06:51 UTC, someotherself commented on src/encryptedfs.rs
> +        if self.is_read_only().await {
Removed as well.

2024-08-24 16:41 UTC, radumarias approved these changes
I you added to all the places from the issue then it's fine

2024-08-24 16:43 UTC, radumarias approved these changes

2024-08-24 16:43 UTC, merged