[185]Refactor copy file rage function
xoriors/rencfs pull request #197
Opened 2024-09-09 20:10 UTC by cristiborta

Issue [185](https://github.com/radumarias/rencfs/issues/185): Refactor copy file rage function

2024-09-09 22:35 UTC, radumarias requested changes

2024-09-09 22:35 UTC, radumarias commented on src/encryptedfs.rs
> +pub struct InodeMetaData {
maybe have name like `CopyFileRangeReq`

2024-09-09 22:35 UTC, radumarias commented on src/encryptedfs.rs
> -        src_fh: u64,
have these 2 also in `CopyFileRangeReq`

2024-09-10 17:12 UTC, radumarias approved these changes

2024-09-10 18:06 UTC, radumarias approved these changes

2024-09-10 18:21 UTC, merged

2024-09-10 19:16 UTC, Veetaha commented on src/encryptedfs.rs
> +pub struct CopyFileRangeReq {
Hi! I found this through the dependency graph feature of Github :eyes:.

Just wanted to leave a comment, that for such a simple case you could avoid writing the `new` method manually. Instead you can just add a `#[derive(bon::Builder)]` to the struct. I recommend using the `#[builder]` with the `new()` method only for complicated cases when there needs to be some more logic during building.

Note that switching between `#[derive(bon::Builder)]` and `#[builder]` on method new is completely [compatible](https://elastio.github.io/bon/guide/compatibility#switching-between-derive-builder-and-builder-on-the-new-method), if you use the same method arguments for the method `new` as the are fields on the struct