Move from `secrecy` to `shush`
xoriors/rencfs pull request #201
Opened 2024-09-14 19:07 UTC by Eyob94

This commit will
- Use the newly created `shush-rs` crate to replace `secrecy` adding better memory protection

2024-09-14 19:18 UTC, radumarias requested changes

2024-09-14 19:18 UTC, radumarias commented on examples/change_password_cli.rs
> +    let new_password = SecretString::from_str(read_password().unwrap().as_str()).unwrap();
maybe keep name as simply `from` this is how I've seen in other libs

2024-09-14 19:18 UTC, radumarias commented on examples/crypto_write_read.rs
same, just `from`

2024-09-14 19:18 UTC, radumarias commented on src/crypto.rs
> +    hash(data.expose_secret().as_slice())
maybe impl Deref for SecretBox and it should auto deref

2024-09-14 19:21 UTC, Eyob94 commented on examples/change_password_cli.rs
> +    let new_password = SecretString::from_str(read_password().unwrap().as_str()).unwrap();
This is an implementation of the `FromStr` trait however

2024-09-14 19:21 UTC, Eyob94 commented on examples/crypto_write_read.rs
Can do for `vec`, since this will be a breaking change on the crate itself, I'll have both, what do you think?

2024-09-14 19:21 UTC, radumarias commented on examples/crypto_write_read.rs
then it's fine

2024-09-14 19:26 UTC, radumarias commented on examples/crypto_write_read.rs
for 1k usages I think it's reasonable breaking change, as most of downloads are bots like from lib.rs, or increase major if you think

2024-09-16 15:13 UTC, Eyob94 commented on src/crypto.rs
> +    hash(data.expose_secret().as_slice())
Done

2024-09-16 15:28 UTC, idi8-t-here approved these changes
works like a charm, pretty awesome. Keep it up bro 💪

2024-09-16 15:31 UTC, radumarias approved these changes

2024-09-16 15:33 UTC, merged