Feature/check tmp files
xoriors/rencfs pull request #220
Opened 2024-10-09 18:40 UTC by srzamfir

Preliminary draft: 
* if any test panics unmount fails
* some syntax warnings

2024-10-10 08:24 UTC, radumarias requested changes

2024-10-10 08:24 UTC, radumarias commented on tests/rencfs_itest.rs
> +mod common;
maybe have suggestive name for this file

2024-10-10 08:24 UTC, radumarias commented on tests/rencfs_itest.rs
> +    assert!(res.is_ok(), "failed to delete [{}]", res.err().unwrap());
shouldn't we check that tmp was deleted? or what is the purpose of these tests?

2024-10-15 15:07 UTC, srzamfir commented on tests/rencfs_itest.rs
> +mod common;
done .. this is now mount_setup

2024-10-15 15:11 UTC, srzamfir commented on tests/rencfs_itest.rs
> +    assert!(res.is_ok(), "failed to delete [{}]", res.err().unwrap());
the test setup assumes that we mount in /tmp/rencfs/mnt where we interact programmatically with various fs functions : e.g. we create a file, write some contents, rename it, check its attributes , add a directory and so on; at the end of each test we clean up 
the temp check test actually runs the suggested scenario and compares the before and after contents of /tmp => the results seem to show we don't leak anything there

2024-10-15 15:35 UTC, radumarias commented
I see it's still draft, let me know when it's ready for review, but looks ok to me

2024-10-16 08:31 UTC, srzamfir commented
it seems the build is still broken ...  not sure what happens there ; i'm guessing it has something to do with the config

2024-10-16 08:38 UTC, radumarias commented
something related to this branch?

2024-10-18 07:48 UTC, srzamfir commented
The build still fails on the AUR step but i believe that's already another topic

2024-10-21 14:08 UTC, radumarias approved these changes

2024-10-21 14:08 UTC, merged