Resolves #214: Restrict some characters from node names
xoriors/rencfs pull request #251
Opened 2024-12-07 08:47 UTC by Ropler6

Solves issue #214 
Added name-validating functions in `/src/mount/linux.rs` and `/src/encryptedfs.rs`.
Use said functions in multiple methods to check for `'/'` and `'\'` characters.

2024-12-07 10:01 UTC, radumarias requested changes

2024-12-07 10:01 UTC, radumarias commented on src/encryptedfs.rs
> +            return Err(FsError::InvalidInput("invalid file name"));
Have two conditions and explicitly say in the error message what char is invalid, like
```
if filename.contains('/') {
    Err(FsError::InvalidInput("'/' not allowed in the filename"))
} else if filename.contains('/') {
    Err(FsError::InvalidInput("'\\' not allowed in the filename"))
} else {
    Ok(())
}
```

You don't need ret `bool` as you ret Err, just return nothing `FsResult<()>`.

2024-12-08 15:04 UTC, radumarias requested changes

2024-12-08 15:04 UTC, radumarias commented on src/encryptedfs.rs
> +        self.validate_filename(&new_name.expose_secret().to_string())?;
if it's called in all places from SecretVec better have param as SecretVec

2024-12-08 15:04 UTC, radumarias commented on src/mount/linux.rs
> +    fn validate_filename(&self, filename: &OsStr) -> Result<bool> {
we don't need here, it's enough in EncryptedFs

2024-12-09 17:05 UTC, radumarias commented
@Ropler6 any updates on this?

2024-12-09 17:15 UTC, Ropler6 commented
Will start working on it tomorrow

2024-12-10 12:48 UTC, closed without merging