Split README file
xoriors/rencfs pull request #253
Opened 2024-12-07 21:16 UTC by IoanaAlexandraO

2024-12-08 20:22 UTC, radumarias requested changes

2024-12-08 20:22 UTC, radumarias commented on docs/Altenatives.md
> +#Alternatives
space after `#`

2024-12-08 20:22 UTC, radumarias commented on docs/Cipher_comparison.md
> +Cipher comparison
add `#`

2024-12-08 20:22 UTC, radumarias commented on docs/Stack.md
> +## Stack
just one `#`

2024-12-09 20:35 UTC, radumarias commented
@IoanaAlexandraO any updates on this?

2024-12-09 21:05 UTC, radumarias requested changes

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- Motivation
use `##`

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- A short story
use `##`

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- A short story
and for all `-` in main `#` use sub-chapter levels like `##`, `###`...

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- [KEY features](docs/Key_features.md)
`# Key...`

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- GUI
remove

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- [Alternatives](docs/Alternatives.md)
use `#`

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- Docs
link to `docs` folder

2024-12-09 21:05 UTC, radumarias commented on README.md
> +- What separates us
move to `Alternatives` from above as `## What separates us`

2024-12-09 21:05 UTC, radumarias commented on docs/Key_features.md
> +- `Security` using well-known audited `AEAD` cryptography primitives;
Replace the lines from here in the bigger list. Don't delete the list just replace corresponding ones

```
- [WIP] [Data integrity, data is written with WAL to ensure integrity even on crash or power loss](https://github.com/radumarias/rencfs/issues/48)
- [WIP] [Hide all info for enhanced privacy; all metadata, content, file name, file size, *time fields, files count, and directory structure is encrypted](https://github.com/radumarias/rencfs/issues/53)
- Safely manage credentials in memory with mlock(2), mprotect, zeroize, and expiry to mitigate cold boot attacks;
- [WIP] [Generate unique nonce in offline mode](https://github.com/radumarias/rencfs/issues/47)
- [WIP] [Add file inode and chunk index to AAD](https://github.com/radumarias/rencfs/issues/49) This prevents blocks from being copied between or within files by an attacker.
- Fast seek on both reads and writes;
- Exposed with FUSE;
- [WIP] [Handle long file names](https://github.com/radumarias/rencfs/issues/47)
- [WIP] [Abstraction layer for Rust File and fs API to use it as lib to switch to using encrypted files by just changing the use statements](https://github.com/radumarias/rencfs/issues/97)
- [WIP] [Abstraction layer to access the storage with implementations for desktop, Wasm, Android, and iOS and the ability to write your own implementation](https://github.com/radumarias/rencfs/issues/111)
```

2024-12-09 21:05 UTC, radumarias commented on docs/Altenatives.md
> +#Alternatives
rename the file and add missing `r` `Alternatives.md`

2024-12-09 21:08 UTC, radumarias requested changes

2024-12-09 21:08 UTC, radumarias commented on docs/Key_features.md
> +## Key features
move these directly in readme file as these are selling points, are important for users to see

2024-12-09 21:29 UTC, radumarias requested changes

2024-12-09 21:29 UTC, radumarias commented on README.md
> +# Future and Considerations
`# Next steps`

2024-12-09 21:29 UTC, radumarias commented on README.md
> +- Future
remove

2024-12-09 21:29 UTC, radumarias commented on README.md
> +    The plan is to implement it also on macOS and Windows
move in list

2024-12-09 21:29 UTC, radumarias commented on README.md
> +- Performance
Add `# Considerations`
and `## Performance`

2024-12-09 21:29 UTC, radumarias commented on README.md
> +- [⚠️ Security ](docs/Security.md)
move after `Performance`

2024-12-09 21:29 UTC, radumarias commented on README.md
> +- [Considerations](docs/Considerations.md)
rename to `Others`

2024-12-09 21:29 UTC, radumarias commented on README.md
> +- Blog and tutorial
Move to the bottom like
```
# Follow us

## Blog and tutorial
```

2024-12-11 20:06 UTC, radumarias requested changes

2024-12-11 20:06 UTC, radumarias commented on docs/Alternatives.md
>  - [File Lock PEA](https://eck.cologne/peafactory/en/html/file_pea.html)
where are the rest? See here the full list https://github.com/radumarias/rencfs?tab=readme-ov-file#alternatives

2024-12-11 20:17 UTC, IoanaAlexandraO commented on docs/Alternatives.md
>  - [File Lock PEA](https://eck.cologne/peafactory/en/html/file_pea.html)
There are 15 bullets both sides.

2024-12-11 20:20 UTC, radumarias approved these changes

2024-12-11 20:22 UTC, merged